POST http://127.0.0.1:3001/api
Content-Type: application/json

{
    "test" : true,
    "number" : 12,
    "String" : "HELLOW"
}
###
GET http://127.0.0.1:3001/api
Content-Type: application/json


###
PUT http://127.0.0.1:3001/api
Content-Type: application/json

###
DELETE http://127.0.0.1:3001/api

